name: package-ubuntu

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add deb-src
        run: |
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt update

      - name: Install build deps
        run: |
          sudo apt build-dep libvtk9-qt-dev

      - name: Install sources
        run: |
          sudo apt source libvtk9-qt-dev

      - name: Build
        run: |
          sudo apt -b source libvtk9-qt-dev

      - name: Upload package as artifact
        uses: actions/upload-artifact@v6
        with:
          path: ./*.deb
