name: package-ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install build deps
        run: |
          apt build-dep libvtk9-qt-dev

      - name: Install sources
        run: |
          apt source libvtk9-qt-dev

      - name: Build
        run: |
          apt -b source libvtk9-qt-dev

      - name: Upload package as artifact
        uses: actions/upload-artifact@v6
        with:
          path: ./*.deb
